In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b=np.append(a,6)
print(b)

[1 2 3 4 5 6]


In [4]:
c= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
c= np.append(c,11) #adding a  single data
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [6]:
print(c)


[ 1  2  3  4  5  6  7  8  9 10 11]


In [7]:
#appending rows in 2d
x= np.array([[1,2,3,4,5],[6,7,8,9,10]])
y =[[11,12,13,14,15]] #all rows should have equal no of elements.
z=np.append(x,y,axis=0)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
#appending rows using vstack,stacks dont takes axis
x= np.array([[1,2,3,4,5],[6,7,8,9,10]])
y =[[11,12,13,14,15]] #all rows should have equal no of elements.
z=np.vstack([x,y]) 
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
#appending  columns  
x=np.array( [[1,2,3,],[4,5,6]])
y=[[7],[8]] #adds 7 to 0th row and 8 to 1st row.
z= print(np.append(x,y,axis=1))

[[1 2 3 7]
 [4 5 6 8]]


In [10]:
#appending column  using hstack
x= np.array([[1,2,3,],[4,5,6]])
y =[[7],[8]]
z= print(np.hstack([x,y]))

[[1 2 3 7]
 [4 5 6 8]]


In [11]:
#using the insert method
x= np.array([1,2,3,4,5])
y=[9]
print(np.insert(x,1,y))

[1 9 2 3 4 5]


In [12]:
#using the insert method, using axis to keep the array seperate
x= np.array([[1,2,3],[4,5,6]])
y=[9,10]
print(np.insert(x,1,y,axis=1))

[[ 1  9  2  3]
 [ 4 10  5  6]]


In [13]:
##using the insert method, using axis to keep the array seperate
#adding multiple rows using axis
x= np.array([[1,2,3],[4,5,6]])
y=[[8,9,10],[11,12,13]]
print(np.insert(x,2,y,axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]]


In [14]:
x= np.array([[1,2,3],[4,5,6]])
y=[[8,9,10],[11,12,13]]
print(np.hstack([x,y]))

[[ 1  2  3  8  9 10]
 [ 4  5  6 11 12 13]]


In [15]:
x= np.array([1,2,3,4,5])
print(np.delete(x,4))


[1 2 3 4]


In [16]:
x= np.array([1,2,3,4,5])
print(np.delete(x,[3,4]))

[1 2 3]


In [17]:
x= np.array([1,2,3,4,5])
print(np.delete(x,range(len(x)))) #len(x) means legth of x
#range(len(x)) ,means allindices in array
#np.delete(in array x, all elements)
#or

[]


In [18]:
x=np.array([1,2,3,4,5])
print(np.delete(x,np.s_[:]))

[]


In [19]:
x= np.array([[1,2,3],[4,5,6]])
print(np.delete(x,np.s_[:]))  #deletes all element of 2d array

[]


In [20]:
x= np.array([
    [1,2,3],
    [4,5,6]])
print(np.delete(x,[0],axis=0)) #deletes the 0th row

[[4 5 6]]


In [21]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])
print(np.delete(x,[0,1],axis=0)) #deletes the 0,1th row

[[7 8 9]]


In [22]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])
print(np.delete(x,[0],axis=1)) #to  delete entire rows or column ,mention bracket and 
#just mention the indices,and if you want  to  delete rows=>axis=0 ,
#if want to  delete columns, axis=1

[[2 3]
 [5 6]
 [8 9]]


In [23]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])

print(np.delete(x,1,axis=0)) ,# here indice 1 is for rows ,beacuse axis is 0.

[[1 2 3]
 [7 8 9]]


(None,)

In [24]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])

print(np.delete(x,1,axis=1))# here indice 1 is for column ,beacuse axis is 1.

[[1 3]
 [4 6]
 [7 9]]


In [25]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])

print(np.delete(x,2,axis=0))

[[1 2 3]
 [4 5 6]]


In [26]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])

print(np.delete(x,2,axis=1))


[[1 2]
 [4 5]
 [7 8]]
