In [4]:
import numpy as np


In [18]:
#create a python array
a = np.array([11,22,33,44,55])
print(a)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(len(a)) #gives the number of element in 1d array


[11 22 33 44 55]
5
(5,)
int32
1
5


In [11]:
b= a.astype(float) #converting array into float,storing it in b,printing b.
print(b)

[11. 22. 33. 44. 55.]


In [12]:
print(b)

[11. 22. 33. 44. 55.]


In [14]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(len(a))  #gives the no of rows


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
(2, 5)
int32
2


In [15]:
b= a.astype(float) #use to convert datatype
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [16]:
c= b.astype(int)
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
print(len(c))  #gives the no of arrays in 2d array

2


In [19]:
print(type(c))

<class 'numpy.ndarray'>
