In [1]:
import numpy as np
#axis 0 means stack two  rows one after another  vertically(along rows)
#axis 1 means stacks arrays horizontally  (along columnns)

In [2]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
row0 =print(a[0])
row1 =print(a[1])
row2 =print(a[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [7]:
sumAxis0 = np.sum(a,axis=0)
print(sumAxis0) #prints the sume of rows vertically downword

[12 15 18]


In [9]:
sumAxis1= np.sum(a,axis=1)
print(sumAxis1)
#prints the sum of rows horizontally.

[ 6 15 24]


In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=  np.array([10,11,12])
c= np.concatenate((a,[b]),axis=0)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [114]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array( [10,11,12])
c= np.concatenate((a,[b]),axis=0) 
#axis 0 , beacuse a is a 2d array, and b  is  a 1d array,cannot align column wise
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
c= np.concatenate((a,b),axis=0)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [47]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
c= np.concatenate((a,b),axis=1)#concatenatets rows vertically downward.
print(c)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
c= np.concatenate((a,b),axis=0)
print(c)
print("SumOfaxis0" ,np.sum(c,axis=0))
print("SumOfaxis1" ,np.sum(c,axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
SumOfaxis0 [51 57 63]
SumOfaxis1 [ 6 15 24 33 42 51]


In [115]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
c= np.concatenate((a,b),axis=1)
print(c)
print("SumOfaxis0" ,np.sum(c,axis=0))
print("SumOfaxis1" ,np.sum(c,axis=1))

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
SumOfaxis0 [12 15 18 39 42 45]
SumOfaxis1 [39 57 75]


In [64]:
#vstack ,stacks arrays vertically
a= np.array([[1,2,3,],[4,5,6]])
b = np.array([[7, 8, 9],[10, 11, 12]])
c= np.vstack([a,b])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [66]:
#vstack ,stacks arrays horizontally (appends b to a,at right side)
a= np.array([[1,2,3,],[4,5,6]])
b = np.array([[7, 8, 9],[10, 11, 12]])
c= np.hstack([a,b])
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [81]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [9, 10, 11]])
c = np.array([[12, 3, 14], [15, 16, 17]])
d = np.array([[18, 19, 20], [21, 22, 23]])

# Vertical stacking
vertical_stack = np.vstack([a, b, c, d])
print("The new stack using vertical stack is \n:", vertical_stack)

# Horizontal stacking(The columns of a, b, c, and d are appended side by side:)
horizontal_stack = np.hstack([a, b, c, d])
print("The new stack using horizontal stack is \n:", horizontal_stack)


The new stack using vertical stack is 
: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]
 [12  3 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
The new stack using horizontal stack is 
: [[ 1  2  3  7  8  9 12  3 14 18 19 20]
 [ 4  5  6  9 10 11 15 16 17 21 22 23]]


#Append function numpy

In [92]:

#if we dont use axis it , while using append, flattens the array
#numpy.append(arr, values, axis=None)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [9, 10, 11]])
c= np.append(a,b) 
print(c)

[ 1  2  3  4  5  6  7  8  9  9 10 11]


In [83]:
#numpy.append(arr, values, axis=None) #if we use, it appends, but remains 2d

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [9, 10, 11]])
c= np.append(a,b,axis=0) #stacks vertically
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


In [90]:
#numpy.append(arr, values, axis=None)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [9, 10, 11]])
c= np.append(a,b,axis=1) 
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6  9 10 11]]


In [106]:
a= a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9],[10,11,12]])
c=np.append(a,b)
print(c) #prints the flatten appended array
c= np.append(a,b,axis=0)
print(c)#prints the array, in 2d
c= np.append(a,b,axis=1)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [112]:
a= a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])
c= np.append(a,b) #axis wont work, beacuse dimensions are different
print(c)

[1 2 3 4 5 6 7 8 9]


In [118]:
a= np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([5,6,7])
c= np.insert(a,1,b)
print(c)

[1 5 6 7 2 3 4 5 6]


In [119]:
a= np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([5,6,7])
c= np.insert(a,1,b,axis=0)
print(c)

[[1 2 3]
 [5 6 7]
 [4 5 6]]


In [123]:
a= np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([5,6,7])
#c= np.insert(a,1,b,axis=1)  
#print(c)  #gives error


In [128]:
a= np.array([1, 2,3,4, 5, 6])
b=np.array([7,8,9])
print(np.insert(a,0,b))
print(np.insert(a,1,b))
print(np.insert(a,2,b))
print(np.insert(a,3,b))

[7 8 9 1 2 3 4 5 6]
[1 7 8 9 2 3 4 5 6]
[1 2 7 8 9 3 4 5 6]
[1 2 3 7 8 9 4 5 6]
