In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [6]:
print(a.shape)

(5,)


In [7]:
print(a.size)

5


In [9]:
print(a[0])

1


In [10]:
print(a[1])

2


In [11]:
print(a[0:3]) #slicing 

[1 2 3]


In [13]:
print(a[1:4])

[2 3 4]


In [14]:
print(a[3:])

[4 5]


In [16]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [17]:
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
print(b.shape)

(2, 5)


In [19]:
print(b.size)

10


In [28]:
#Printing the all the elements of 0th row.
print(b[0,0])
print(b[0,1])
print(b[0,2])
print(b[0,3])
print(b[0,4])


1
2
3
4
5


In [31]:
#Printing the all the elements of 1st row.
print(b[1,0])
print(b[1,1])
print(b[1,2])
print(b[1,3])
print(b[1,4])


6
7
8
9
10


In [52]:
#slicing specific row and column
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
#slicing first row, last two elements
print(b[0,0:3])


[1 2 3]


In [57]:
print(b[0,3:]) #slicing 0th rows

[4 5]


In [62]:
print(b[0,1:3])#slicing middle two element
print(b[0,2:4])
print(b[0,1:4])

[2 3]
[3 4]
[2 3 4]


In [63]:
print(b[1,0:3]) #slicing 1st row

[6 7 8]


In [65]:
print(b[1,3:])

[ 9 10]


In [70]:
print(b[1,1:3])
print(b[1,2:4])
print(b[1,1:4])

[7 8]
[8 9]
[7 8 9]


In [82]:
print(b[:,:]) #slicing all rows and columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [85]:
print(b[:,2:4])  #for all rows we only want 3th and 4th element

[[3 4]
 [8 9]]


In [86]:
c = np.array([11,22,33,44,55])
print(c)
print(c.size)
print(c.shape)
print(c.dtype) #data type
print(c.ndim) #number of dimensions

[11 22 33 44 55]
5
(5,)
int32
1
