In [2]:
import numpy as np


In [ ]:
#axis =0,Operates along rows (down the columns).
#axis=1,Operates along columns (across the rows).

In [2]:
a= np.array([11,12,13,14,15])
b=np.array([21,22,23,24,25])
print(a)
print(b)

[11 12 13 14 15]
[21 22 23 24 25]


In [3]:
print(a+b)

[32 34 36 38 40]


In [4]:
print(a-b)

[-10 -10 -10 -10 -10]


In [5]:
print(a+b)

[32 34 36 38 40]


In [6]:
print(a/b)

[0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


In [7]:
print(np.sqrt(a))
print(np.sqrt(b))

[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
[4.58257569 4.69041576 4.79583152 4.89897949 5.        ]


In [10]:
c = np.array([[22,25],[26,17]])
d = np.array([[24,26],[56,67]])
print(c)
print(d)

[[22 25]
 [26 17]]
[[24 26]
 [56 67]]


In [11]:
print(c+d)
print(c-d)
print(c/d)

[[46 51]
 [82 84]]
[[ -2  -1]
 [-30 -50]]
[[0.91666667 0.96153846]
 [0.46428571 0.25373134]]


In [13]:
print(np.sqrt(c))
print(np.sqrt(d))

[[4.69041576 5.        ]
 [5.09901951 4.12310563]]
[[4.89897949 5.09901951]
 [7.48331477 8.18535277]]


In [22]:
arr10 =  np.array([ 144 , 529,  576 ,3025 ,4489])
print(np.sqrt(arr10).astype(int))

[12 23 24 55 67]


In [25]:
arr10 =  np.array([ 12 , 23,  24 ,55 ,67])
arr11 = np.array([2])
powerarray= np.power(arr10,arr11)
print(powerarray)

[ 144  529  576 3025 4489]
