In [1]:
import numpy as np

In [2]:
#create an unsorted array
x= np.array([17,55,21,12,14,88,33,46,66])
print(x)

[17 55 21 12 14 88 33 46 66]


In [3]:
y=np.sort(x)  #sort the unsorted array ,save,and print
print(y)

[12 14 17 21 33 46 55 66 88]


In [4]:
#printing array  elements in 1d array
x= np.array([17,55,21,12,14,88,33,46,66])
print(x[0])
print(x[0])
print(x[0])

17
17
17


In [5]:
#searching element in 1d array
x= np.array([17,55,21,12,14,88,33,46,66])
print(np.where(x==55)) #gives index of element

(array([1], dtype=int64),)


In [6]:
x= np.array([17,55,21,12,14,88,33,46,66])
print(np.where(x >40))

(array([1, 5, 7, 8], dtype=int64),)


In [7]:
x= np.array([17,55,21,12,14,88,33,46,66])
print(np.where((x>40) & (x<70))) #gives the indices of number
#greater than 40 and less than  70.

(array([1, 7, 8], dtype=int64),)


In [8]:
x= np.array([17,55,21,12,14,88,33,46,66])
print(np.any(x>50)) #checks if any  element >50  is in array or not
print(np.any(x==80)) 
print()

True
False



In [9]:
x= np.array([17,55,21,12,14,88,33,46,66])
print(np.all(x>50)) #all,  check if element are greater than 50
print(np.all(x>0)) #prints true because all element is greater than 0

False
True


#for 2d array, searaching

In [10]:
#create an unsorted 2d array
x = np.array([[17,55,21,12],[14,88,33,46]])
y=np.sort(x)
print(y)

[[12 17 21 55]
 [14 33 46 88]]


In [11]:
# Find Indices of Specific Values
x = np.array([[17,55,21,12],[14,88,33,46]])
print(np.where(x ==88))  

(array([1], dtype=int64), array([1], dtype=int64))


In [12]:
#Find Indices Based on a Condition
x = np.array([[17,55,21,12],[14,88,33,46]])
print(np.where(x> 50))

(array([0, 1], dtype=int64), array([1, 1], dtype=int64))


In [13]:
#axis =0,Operates along rows (down the columns).
#axis=1,Operates along columns (across the rows).

In [14]:
# Search Along Specific Axes
x = np.array([
    [17,55,21,12],
    [14,88,33,46]])
print(np.max(x,axis=0))
#for both rows, prints the greater number on each column
#12,14=>17
#55,88=>88
#21,33=>33
#12,46=>46 

[17 88 33 46]


In [15]:
x = np.array([
    [17,55,21,12],
    [14,21,33,88]])
print(np.max(x,axis=1))
#prints the maxm number in  each row

[55 88]


In [16]:
x = np.array([
    [17,55,21,12],
    [14,21,44,88]])
print(np.max(x,axis=0))
print(np.argmax(x,axis=0)) #argmax,gives he indices of each max value in each row,
#o,1 represents the row 

[17 55 44 88]
[0 0 1 1]


#Filtering in numpy

In [17]:
x=np.array([5,1,15,20,25])
print(x)

[ 5  1 15 20 25]


In [18]:
filtered_x = x[x>10]
print(filtered_x)

[15 20 25]


In [19]:
x=np.array([5,1,15,20,25])
filtered_x = x[(x>5)&(x<30)]
print(filtered_x)

[15 20 25]


In [20]:
x=np.array([5,1,15,20,25])
filtered_x=x[x>5]
print(filtered_x)

[15 20 25]


In [21]:
x=np.array([5,1,15,20,25])
filtered_x = x[(x>5)&(x<20)]
print(filtered_x)

[15]


In [22]:
#filtering in 2d array

In [23]:
x=np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
filtered_x=x[x[:,0]>3] 
#x[:,0], means for all rows,first column,
#x[:,0],means for all rows,first column,  greater than 3
print(filtered_x)

[[4 5 6]
 [7 8 9]]


In [24]:
#filtering in 2d array
x=np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
filtered_x=x[x[:,:]>4]  #for all rows and column  ,print all element greater than4
print(filtered_x)

[5 6 7 8 9]


In [25]:
x=np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
filtered_x= x[0:2,0]  #for rows, 0,1 ,column 0   
print(filtered_x)

[1 4]


In [26]:
#print values from rows 0 and 1 and all columns where the value is less than 5,
x=np.array([[1, 2, 3],
                   [4, 5, 6],
                [7, 8, 9]])
#first chose 
y  = x[0:2,:] #choose row 0,1 ie, 0:2

z = y[y<3] #apply condition ,<3 
print(z) #print 3

[1 2]
