In [1]:
import numpy as np


In [6]:
a= np.array([10,20,30,40,50])
print(x)

[10 20 30 40 50]


In [7]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.cumsum(a))
print(np.cumprod(a))


150
10
50
[      10      200     6000   240000 12000000]
[ 10  30  60 100 150]
